/** Offline editorial frames; real browser footage is composited by FFmpeg. */
import { chromium } from '@playwright/test';
import { readFile,writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const out=resolve(process.argv[2]);const story=JSON.parse(await readFile(out+'/storyboard.json','utf8'));
const capture=resolve(story.capture);const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});const checks=[];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const overview=(await readFile(capture+'/overview.png')).toString('base64');const architecture=(await readFile('submissions/architecture/rehearsal-serverless.png')).toString('base64');
for(const [i,s] of story.scenes.entries()){
 let content='';
 if(s.kind==='intro')content=`<div class="hero"><span class="eyebrow">TRANSACTION REHEARSAL FOR AI AGENTS</span><h1>When stock changes,<br>can the agent<br><em>still deliver?</em></h1><p>One real browser experiment.<br>A result checked against transaction records.</p></div><div class="preview"><img src="data:image/png;base64,${overview}"></div><div class="preview-note">DASHBOARD PREVIEW · LIVE WALKTHROUGH FOLLOWS</div>`;
 if(s.kind==='learning')content='<div class="hero learning"><span class="eyebrow">B3 / PRACTICE + PEER REVIEW</span><h1>An isolated world.<br>A separate<br><em>reviewer.</em></h1><p>One shared model-usage ledger.<br>The live clock starts after practice.</p></div>';
 if(s.kind==='result')content='<div class="takeaway"><b>Independent journal replay</b><span>Quantities · recipient · budget · delivery timing</span></div>';
 if(s.kind==='timeline')content='<div class="takeaway timeline"><b>Practice result: NO_CHANGE</b><span>This run kept its existing policy. One demo is not an efficacy benchmark.</span></div>';
 if(s.kind==='architecture')content=`<div class="arch-copy"><span class="eyebrow">AWS SERVERLESS</span><h1>A bounded run.<br><em>Durable<br>evidence.</em></h1><p>AgentCore + Nova 2 Lite<br>Lambda + DynamoDB<br>Step Functions + S3</p><small>Editable draw.io included.<br>Storage and requests remain metered.</small></div><img class="architecture" src="data:image/png;base64,${architecture}">`;
 if(s.kind==='end')content='<div class="closing"><span class="eyebrow">TRY THE LIVE LAB</span><h1>Rehearse.<br>Observe.<br><em>Verify.</em></h1><div class="url">d1u9yhii3gor6j.cloudfront.net</div><p>Choose a condition. Watch the purchase. Inspect the evidence.</p></div><div class="end-note"><b>Source + evidence + AWS architecture</b><p>Amazon Nova 2 Lite · Strands Agents · AgentCore</p><small>Synthetic POC · finite shared demo allowance</small></div>';
 if(story.product==='preflight' && s.kind==='intro')content=`<div class="hero"><span class="eyebrow">BEFORE THE AGENT ACTS</span><h1>See the impact.<br><em>Then decide.</em></h1><p>Rehearse a transaction plan.<br>Get evidence before execution.</p></div><div class="preview"><img src="data:image/png;base64,${overview}"></div><div class="preview-note">ACTUAL DASHBOARD · SYNTHETIC SHOPPING SCENARIO</div>`;
 if(story.product==='preflight' && s.kind==='end')content='<div class="closing"><span class="eyebrow">TRY THE LIVE PREFLIGHT</span><h1>Plan.<br>Measure.<br><em>Decide.</em></h1><div class="url">d1u9yhii3gor6j.cloudfront.net</div><p>See the consequence before the commitment.</p></div><div class="end-note"><b>Zero external orders placed</b><p>Nova planning · isolated simulations<br>Independent evidence · explicit decision</p><small>Synthetic POC · no Amazon connector</small></div>';
 const mode=s.source_start!==undefined?'ACTUAL CHROME RECORDING · ORIGINAL SPEED':'REHEARSAL · SYNTHETIC TRANSACTIONS';
 const html=`<!doctype html><html lang="en"><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;width:1920px;height:1080px;background:#0b121e;color:#f5f6f7;font-family:Arial,sans-serif;overflow:hidden}header{position:absolute;top:25px;left:72px;right:72px;display:flex;align-items:center;justify-content:space-between;color:#aab4c2;font-size:15px;letter-spacing:2px}header b{color:#e3bf65;font-size:24px;letter-spacing:-.3px}h2{position:absolute;top:59px;left:72px;font-size:34px;letter-spacing:-.6px;margin:0;font-weight:600}.hero{position:absolute;left:80px;top:240px;width:900px}.eyebrow{color:#e3bf65;letter-spacing:3px;font-size:15px;font-weight:700}h1{font-size:72px;line-height:1.12;letter-spacing:-2.6px;font-weight:600;margin:27px 0 32px}em{font-style:normal;color:#e3bf65}p{font-size:23px;line-height:1.65;color:#aeb9c7}.preview{position:absolute;top:244px;left:1020px;width:820px;height:530px;border:1px solid #526073;border-radius:12px;overflow:hidden}.preview img{width:100%;margin-top:0}.preview-note{position:absolute;left:1020px;top:797px;color:#8b9bad;font-size:13px;letter-spacing:1px}.learning{top:240px;width:900px}.learning h1{font-size:64px}.takeaway{position:absolute;top:858px;left:100px;right:100px;display:flex;justify-content:space-between;border-top:1px solid #3b4759;padding-top:24px;font-size:24px}.takeaway b{color:#e3bf65}.takeaway span{color:#adb8c8}.timeline{top:805px;flex-direction:column;gap:18px}.arch-copy{position:absolute;left:72px;top:250px;width:460px}.arch-copy h1{font-size:53px}.arch-copy p{font-size:22px}.arch-copy small{font-size:15px;line-height:1.6;color:#8190a2}.architecture{position:absolute;left:570px;top:142px;width:1280px;height:814px;object-fit:contain;background:#fff;border-radius:8px}.closing{position:absolute;left:100px;top:190px}.closing h1{font-size:96px;line-height:1.01}.url{display:inline-block;padding:18px 23px;background:#e3bf65;color:#142031;font-size:30px;border-radius:6px}.end-note{position:absolute;left:1120px;top:470px;width:650px;border-left:3px solid #e3bf65;padding-left:30px}.end-note b{font-size:25px}.end-note p{font-size:21px}.end-note small{font-size:16px;color:#91a0b2}footer{position:absolute;left:72px;right:72px;top:983px;display:flex;justify-content:space-between;font-size:13px;letter-spacing:1px;color:#8e9daf}.progress{position:absolute;left:72px;top:1014px;width:1776px;height:2px;background:#293548}.progress i{display:block;height:2px;background:#e3bf65;width:${(i+1)/story.scenes.length*100}%}</style><body><header><b>r. &nbsp; rehearsal</b><span>${esc(s.tag)}</span></header><h2>${esc(s.title)}</h2>${content}<footer><span>${mode}</span><span>${i+1} / ${story.scenes.length} &nbsp; · &nbsp; AMAZON NOVA 2 LITE</span></footer><div class="progress"><i></i></div></body></html>`;
 await p.setContent(html,{waitUntil:'load'});await p.screenshot({path:out+`/frame-${i}.png`});checks.push({scene:i,title:s.title,overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight)});
}
// Raster text overlays avoid relying on optional FFmpeg text/subtitle filters.
for(const [i,s] of story.scenes.entries())for(const [j,cue] of s.caption_cues.entries()){
 await p.setContent(`<html><style>body{margin:0;background:transparent;font-family:Arial,sans-serif}.caption{position:absolute;left:72px;right:72px;bottom:19px;text-align:center;color:#f5f6f7;font-size:29px;line-height:35px}</style><div class="caption">${esc(cue.text)}</div></html>`);
 await p.screenshot({path:out+`/caption-${i}-${j}.png`,omitBackground:true});
}
await p.setViewportSize({width:740,height:34});
await p.setContent('<html><style>body{margin:0;background:#0b121e;color:#e3bf65;font:13px Arial;letter-spacing:1px;padding-top:6px}</style>PAUSED FRAME · RECORDED FOOTAGE</html>');
await p.screenshot({path:out+'/held-label.png'});
await writeFile(out+'/frame-checks.json',JSON.stringify(checks,null,2));await b.close();
