import { useEffect, useState } from 'react';
import './cloud.css';
type Usage = { model_calls: number; recorded_micro_usd: number; unresolved_reserved_micro_usd: number; recorded_total_tokens: number };
type Run = { run_id: string; method: string; case: string; status: string; finalized: boolean; progress?: { usage?: Usage }; runtime?: { phase: string; runtime_status?: string; learning_status?: string; usage?: Usage }; snapshot?: { tick: number; version: number; goal: { items: Record<string, number>; budget: number; deadline_tick: number }; inventory: Record<string, number>; balance: { spent: number; reserved: number; available: number }; suppliers: string[]; offers: Record<string, { items: Record<string, { price: number; stock: number }>; shipping: number; lead_ticks: number }>; orders: { order_id: string; supplier: string; amount: number; status: string }[] }; events?: { kind: string; tick?: number; [key: string]: unknown }[]; verification?: { verdict: { status: string; errors: string[] }; usage_known: boolean; runtime_session_stop_requested: boolean } };
const methods = [ ['B0', 'Rules only', 'A fixed purchasing policy. No AI calls.'], ['B1', 'Direct agent', 'Nova buys directly in the live experiment.'], ['B2', 'Practice first', 'One agent rehearses before the live purchase.'], ['B3', 'Peer review', 'An independent reviewer checks the practice policy.'] ];
const cases: Record<string, string> = { normal: 'Normal supply', 'stock-change': 'Stock disappears', 'price-change': 'Price increases', unavailable: 'Tents unavailable', 'untrusted-supplier': 'Untrusted supplier message' };
const money = (n = 0) => `$${(n / 1e6).toFixed(5)}`;
export function CloudApp() {
  const [method, setMethod] = useState('B1'), [scenario, setScenario] = useState('stock-change');
  const [id, setId] = useState(new URLSearchParams(location.search).get('run') ?? '');
  const [run, setRun] = useState<Run | null>(null), [error, setError] = useState(''), [starting, setStarting] = useState(false), [updated, setUpdated] = useState(0);
  const [request, setRequest] = useState<string | null>(null);
  useEffect(() => { if (!id) return; let alive = true; const controller = new AbortController();
    async function poll() { try { const r = await fetch(`/api/experiments/${encodeURIComponent(id)}`, { signal: controller.signal, cache: 'no-store' }); const body = await r.json(); if (!r.ok) throw Error(body.error ?? 'Could not load this experiment.'); if (alive) { setRun(body); setUpdated(Date.now()); setError(''); if (body.finalized) clearInterval(timer); } } catch (e) { if (alive) setError(e instanceof Error ? e.message : 'Connection interrupted.'); } }
    void poll(); const timer = setInterval(poll, 2000); return () => { alive = false; controller.abort(); clearInterval(timer); };
  }, [id]);
  async function start() { setStarting(true); setError(''); const key = request ?? crypto.randomUUID(); setRequest(key);
    try { const r = await fetch('/api/experiments', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ request_id: key, method, scenario }) }); const body = await r.json(); if (!r.ok) throw Error(body.error === 'DEMO_BUSY_OR_LIMIT_REACHED' ? 'The demo is busy or its shared allowance has been reached. Try again later.' : body.error ?? 'Could not start the experiment.'); setRun(null); setId(body.run_id); history.replaceState({}, '', `?run=${body.run_id}`); setRequest(null); }
    catch (e) { setError(e instanceof Error ? e.message : 'The start response was interrupted. Retry to recover the same experiment.'); } finally { setStarting(false); }
  }
  const s = run?.snapshot, usage = run?.runtime?.phase === 'FINISHED' ? run.runtime.usage : run?.progress?.usage;
  const total = s ? Object.entries(s.goal.items).reduce((n, [k, q]) => n + Math.min(s.inventory[k] ?? 0, q), 0) : 0;
  const running = starting || !!run && !run.finalized;
  const verdict = run?.verification?.verdict.status;
  return <div className="cloud-app"><header className="cloud-header"><a href="/" className="cloud-brand"><b>r.</b> rehearsal <span>/ live lab</span></a><span className="cloud-tag">AWS SERVERLESS · AMAZON NOVA 2 LITE</span></header>
    <main className="cloud-main"><div className="cloud-intro"><div><p className="cloud-kicker">PRACTICE BEFORE THE REAL COMMITMENT</p><h1>Can the agent still deliver<br />when the world changes?</h1><p>Give an agent a fixed goal. Change the conditions.<br />Check what actually arrived, with an independent transaction audit.</p></div><div className="cloud-goal"><span>THE MISSION</span><strong>3 tents + 6 lights</strong><p>500 synthetic credits · 90-second purchase window</p><small>Practice happens before the purchase clock starts.</small></div></div>
    <section className="cloud-setup" aria-label="Experiment setup"><div className="cloud-section-title"><span>01 / DESIGN AN EXPERIMENT</span><small>Synthetic transactions · no real purchases</small></div><div className="cloud-methods">{methods.map(([key, title, description]) => <button key={key} className={method === key ? 'selected' : ''} disabled={running || !!request} onClick={() => setMethod(key)} aria-pressed={method === key}><span>{key}</span><strong>{title}</strong><small>{description}</small></button>)}</div><div className="cloud-controls"><label>Live condition<select value={scenario} disabled={running || !!request} onChange={e => setScenario(e.target.value)}>{Object.entries(cases).map(([key, title]) => <option key={key} value={key}>{title}</option>)}</select></label><p>One experiment runs at a time.<br />AI runs share a finite demo allowance.</p><button className="cloud-start" onClick={start} disabled={running}>{starting ? 'Starting…' : running ? 'Experiment running…' : request ? 'Recover experiment →' : 'Run experiment →'}</button></div></section>
    {error && <div className="cloud-error" role="alert">{error}</div>}
    <div className="cloud-runbar"><span><i className={running ? 'pulsing' : ''} />{run ? `${run.method} · ${cases[run.case]} · ${run.status.replaceAll('_', ' ')}` : id ? 'Connecting to experiment…' : 'Ready for an experiment'}</span><small>{id ? id : 'Your experiment gets a shareable link.'}</small></div>
    <section className="cloud-results" aria-label="Experiment results"><div className="cloud-world"><div className="cloud-section-title"><span>02 / THE LIVE WORLD</span><small>{s ? `${Math.min(s.tick, s.goal.deadline_tick)} / ${s.goal.deadline_tick} s · revision ${s.version}` : 'Purchase clock not started'}</small></div><div className="cloud-supply">{(s?.suppliers ?? ['A', 'B', 'C']).map(name => { const offer = s?.offers[name]; return <div className="cloud-supplier" key={name}><span>SUPPLIER {name}</span><strong>{offer ? `${offer.items.tent?.price * 3 + offer.items.light?.price * 6 + offer.shipping} cr` : '—'}</strong><p>Full goal including shipping</p><div>{offer ? `${offer.items.tent?.stock} tents · ${offer.items.light?.stock} lights in stock` : 'Awaiting live supply'}</div></div>; })}</div><div className="cloud-route"><span>Suppliers</span><i /><b>Fixed payment ledger</b><i /><span>Event venue</span></div><div className="cloud-balances"><div><small>SPENT</small><strong>{s?.balance.spent ?? 0}<em> / 500 cr</em></strong></div><div><small>RESERVED</small><strong>{s?.balance.reserved ?? 0}<em> cr</em></strong></div><div><small>AI COST (EST.)</small><strong>{money(usage?.recorded_micro_usd)}</strong><em>{usage?.model_calls ?? 0} calls · {usage?.recorded_total_tokens ?? 0} tokens</em>{!!usage?.unresolved_reserved_micro_usd && <em>Unresolved: {money(usage.unresolved_reserved_micro_usd)}</em>}</div></div></div>
    <aside className="cloud-receipt"><span className="cloud-kicker">03 / INDEPENDENT CHECK</span><div className="cloud-quantity">{total}<span> / 9</span></div><h2>Items received</h2>{[['tent', 3], ['light', 6]].map(([item, target]) => <div className="cloud-progress" key={item}><label>{item === 'tent' ? 'Tents' : 'Lights'}<b>{s?.inventory[item] ?? 0} / {target}</b></label><progress max={Number(target)} value={s?.inventory[item] ?? 0} /></div>)}<div className={`cloud-verdict ${verdict === 'COMPLETE' ? 'passed' : ''}`}><strong>{verdict ? verdict === 'COMPLETE' ? 'Delivery independently verified' : verdict === 'INVALID' ? 'Evidence needs review' : 'Goal not fully delivered' : 'Awaiting independent audit'}</strong><p>{verdict ? 'The verifier replayed the transaction journal, including payments and delivery timing.' : 'An agent’s final message does not determine success.'}</p></div></aside></section>
    <section className="cloud-bottom"><div><div className="cloud-section-title"><span>04 / TRANSACTION TIMELINE</span><small>Recorded system events</small></div><div className="cloud-timeline">{run?.events?.length ? [...run.events].reverse().map((e, i) => <div key={`${e.kind}-${i}`}><b>{e.kind.replaceAll('_', ' ')}</b><span>{typeof e.supplier === 'string' ? `Supplier ${e.supplier}` : ''}{typeof e.amount === 'number' ? ` · ${e.amount} cr` : ''}{typeof e.tick === 'number' ? ` · ${e.tick}s` : ''}</span></div>) : <p>Confirmed purchases, payment changes and deliveries will appear here.</p>}</div></div><div className="cloud-execution"><span className="cloud-kicker">AGENT EXECUTION</span><h2>{run?.runtime?.phase?.replaceAll('_', ' ') ?? 'Not started'}</h2><p>{run?.runtime?.learning_status && run.runtime.learning_status !== 'NONE' ? `Practice result: ${run.runtime.learning_status.replaceAll('_', ' ')}` : 'B2 and B3 practice in isolated worlds before entering this live experiment.'}</p><p>{run?.verification?.runtime_session_stop_requested ? 'Runtime session stop requested. Evidence retained.' : 'The run is bounded and the runtime session is stopped at the end.'}</p><small>These controlled experiments do not establish that practice or peer review improves outcomes.</small></div></section>
    <footer className="cloud-footer"><span>Rehearsal · AWS serverless synthetic commerce</span><span>{updated ? `Last received ${new Date(updated).toLocaleTimeString('en-US')}` : 'Amazon Nova 2 Lite + Strands Agents + AgentCore'}</span></footer></main></div>;
}
